name: url_protocol
description: A unified library to register custom URL protocol handlers across all supported platforms.
version: 2.0.0
homepage: https://github.com/lsegal/flutter_url_protocol

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  win32: "^5.0.5"
